/** 界面文案 — 统一简体中文 + 复古未来语气 */
export const copy = {
  app: {
    title: 'GAMESOUND FX',
    tagline: '复古未来 · 音效台',
    statusLive: '系统在线',
  },
  common: {
    on: '开',
    off: '关',
    ok: '确定',
    cancel: '取消',
    delete: '删除',
    save: '保存',
    clear: '清空',
    all: '全部',
    none: '（无）',
    recording: '按键中…',
    pressKey: '请按下快捷键…',
  },
  toolbar: {
    searchPlaceholder: '搜索音效…',
    import: '导入',
    sniffer: '嗅探',
    allSounds: '全部音效',
    groupPrefix: '分组',
    count: (n: number, total: number) => `${n} / ${total}`,
  },
  sound: {
    rec: '录制',
    menu: '菜单',
    removeGroup: '移出分组',
    deleteSound: '删除音效',
    emptyTitle: '没有匹配的音效',
    emptyHint: '换个关键词，或点「导入」添加本地音效',
    deleteTitle: '删除音效',
    deleteMessage: '确定删除这条音效？',
    deleteConfirm: '删除',
  },
  status: {
    selectDevice: '选择输出设备',
    mute: '静音',
    unmute: '取消静音',
    volumeOff: '静音',
  },
  group: {
    manage: '管理分组',
    new: '新建分组',
    namePlaceholder: '分组名称',
    add: '添加',
    edit: '编辑',
    rename: '重命名',
    alreadyUsed: '已占用',
    default: '默认',
    empty: '暂无分组',
    deleteTitle: '删除分组',
    deleteMessage: (name: string) => `确定删除分组「${name}」？`,
  },
  sniffer: {
    target: (name?: string) => `目标：${name || '全部'}`,
    openBrowser: '打开浏览器',
    closeBrowser: '关闭浏览器',
    captured: (n: number) => `已捕获 ${n}`,
    emptyTitle: '暂无捕获',
    emptyHint: '打开爱给网并播放音频，会自动出现在这里',
    saveTitle: '保存音效',
    namePlaceholder: '输入文件名…',
    get: '下载',
    downloading: '下载中',
    saved: '已保存',
    previewStop: '停止',
    previewPlay: '试听',
  },
  settings: {
    title: '设置',
    playPause: '播放 / 暂停快捷键',
    setPlayPause: '设置快捷键',
    playPauseLabel: '播放 / 暂停',
    teamMode: '组队模式',
    pushToTalk: '按键发言',
    teamKey: '发言键',
    teamOnHint: '播放音效时自动按住发言键',
    teamOffHint: '关闭后不再模拟按键',
    valorant: '无畏契约',
    logMonitor: '日志监测',
    valorantHint: '读取 ShooterGame.log，识别回合与爆能器事件',
    pickerPrefix: '事件选择前缀键',
    prefix: '前缀键',
    pickerHint: '按住前缀键 + 数字键，快速选择事件音效',
    shortcuts: '音效快捷键',
    shortcutsEmpty: '尚未绑定快捷键',
    shortcutsHint: '在音效卡片菜单中可绑定',
    help: '操作提示',
    helpLines: [
      '点击音效播放，再点一次停止',
      '在菜单中绑定快捷键与分组',
      'Ctrl+Shift+` 显示 / 隐藏窗口',
      'Ctrl+Shift+Tab 切换紧凑模式',
    ],
    danger: '危险操作',
    resetAll: '重置全部数据',
    resetTitle: '重置全部数据',
    resetMessage: '将清空所有音效、分组与设置，且无法恢复。确定继续？',
    resetConfirm: '重置',
  },
  valorant: {
    title: '无畏契约',
    connected: '已连接',
    disconnected: '未连接',
    bindings: '事件绑定',
    addSound: '添加音效',
    clearLabel: '清空绑定',
    preview: '试听',
    remove: '移除',
    searchPlaceholder: '搜索音效…',
    notFound: '未找到音效',
    bound: '已绑定',
    bind: '绑定',
    pickerTitle: (event: string) => `添加音效 — ${event}`,
  },
} as const;

export const themeColor = {
  cyan: 'var(--accent-cyan)',
  accent: 'var(--accent)',
  pink: 'var(--accent-pink)',
  green: 'var(--accent-green)',
  gold: 'var(--accent-gold)',
  red: 'var(--accent-red)',
  muted: 'var(--text-secondary)',
} as const;
